openstax/aws-ruby

README.md, lib/openstax/aws/deployment_base.rb
The CLI lets you not provide parameter values in a stack update call and instead just reuse the value provided in the prior call.  This PR updates the gem to make that functionality available.
=> Let update stack calls use previous param value

lib/openstax/aws/deployment_base.rb, lib/openstax/aws/extensions.rb, lib/openstax_aws.rb
Also... `present?` because you can't always `!blah.blank?`
=> log bucket name in config

lib/openstax/aws/deployment_base.rb, lib/openstax_aws.rb
Let the key pair name be configurable and accessible via the `Deployment` base class.
=> config key pair name

README.md, lib/openstax/aws/deployment_base.rb
Now instead of just using one `parameters` object per deployment, you can use multiple, e.g. `parameters(id: 'admin_node')` and `parameters(id: 'api_node')`.
=> Support multiple parameters sets per deployment

README.md, lib/openstax/aws/deployment_base.rb, lib/openstax/aws/stack.rb, lib/openstax/aws/stack_factory.rb, spec/deployment_base_spec.rb, spec/stack_factory_spec.rb
* Ensure that deployments without an `env_name` do not generate stack names starting with a hyphen.
* Allow stack names to be manually defined using methods executed in the scope of the deployment
=> env_name-less stack names, stack name overrides

README.md, examples/deployment.rb, lib/openstax/aws/deployment_base.rb, lib/openstax_aws.rb, spec/deployment_base_spec.rb, spec/spec_helper.rb, spec/stack_spec.rb, spec/support/templates/parameter_defaults/app.yml
aws-ruby had been managing some variables as a convenience to the users of this library (e.g. key pair name, log bucket names, hosted zone names, etc).  This PR drops the holding of these variables because they are not applicable to all users, and users can manage them themselves.  Also added methods for defining deployment-wide stack parameter defaults and provides a way for a deployment to override the built-in parameter defaults provided by this gem.  See the README.
=> drop responsibility for non-locally-used params

openstax_aws.gemspec
There's a template in the bin directory used by one of the executables, this PR excludes it from the gem spec's executables list to prevent errors like this when apps bundle:
```
Using openstax_aws 0.1.0 from https://github.com/openstax/aws-ruby.git (at c139dbf@c139dbf)
`/home/ubuntu/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/bundler/gems/aws-ruby-c139dbf3c203/bin/aws_ruby_development.yml` does not exist, maybe `gem pristine openstax_aws` will fix it?
```
=> better spec executables list; exclude templates

lib/openstax_aws.rb
Guard function for verifying template bucket access... to help folks who switch back and forth AWS accounts to get a useful error message if they are using the wrong credentials or targeting the wrong account.
=> Guard function for verifying template bucket access

README.md, lib/openstax/aws/s3_text_file.rb, spec/cassettes/OpenStax_Aws_S3TextFile/deletes_a_file.yml, spec/cassettes/OpenStax_Aws_S3TextFile/does_not_raise_for_deleting_a_non-existent_file.yml, spec/cassettes/OpenStax_Aws_S3TextFile/overwrites_a_file.yml, spec/cassettes/OpenStax_Aws_S3TextFile/raises_for_reading_a_non-existent_file.yml, spec/cassettes/OpenStax_Aws_S3TextFile/reads_a_file.yml, spec/cassettes/OpenStax_Aws_S3TextFile/sets_the_cache_control_header.yml, spec/cassettes/OpenStax_Aws_S3TextFile/writes_a_new_file.yml, spec/s3_text_file_spec.rb
allow setting of cache control header on s3 text file
=> allow setting of cache control header on s3 text file

lib/openstax/aws/packer_1_2_5.rb
For Packer 1.2 use the configured logger.  Matches what Packer 1.4 class does.
=> For Packer 1.2 use the configured logger

lib/openstax/aws/auto_scaling_group.rb, spec/auto_scaling_group_spec.rb
If you call aws set_desired_capacity with a value greater than max_size it raises an aws exception. This limits the increase to the max so that it will run at max_size even if the request is higher.
Picture of the aws exception caused by this issue
=> Limit increase of desired capacity to max_size

README.md, lib/openstax/aws/deployment_base.rb, lib/openstax/aws/secrets.rb, spec/deployment_base_spec.rb, spec/secrets_dsl_spec.rb, spec/secrets_spec.rb
* Adds deployment-level secrets
* Allows secrets to be updated even when they haven't "changed" (helpful for randomly generated secrets that you want to force to regenerate)
See the README changes for more information.
=> add deployment level secrets, minor fixes

README.md, lib/openstax/aws/secrets_factory.rb, lib/openstax/aws/secrets_specification.rb, spec/secrets_factory_spec.rb, spec/secrets_specification_spec.rb
Some of our secrets specification files (e.g. https://github.com/openstax/accounts/blob/master/config/secrets.yml.example) have embedded Ruby.  This PR adds a `preparser { :erb }` option to the secrets `specification` block to allow the specification to handle that ERB.
=> Handled embedded Ruby (ERB) in secrets specifications

README.md, lib/openstax/aws/secrets.rb, spec/secrets_spec.rb
Handle the case where a secrets specification includes an array, e.g. 
```yaml
foo: 
- bar1
- bar2
```
=> handle array secrets

lib/openstax/aws/secrets.rb
With the additional parameters that need to be created with Accounts, I have hit a throttling error multiple times now: 
```
Traceback (most recent call last):
16: from ./create_env:35:in `<main>'
15: from ./create_env:31:in `main'
14: from /accounts-deployment/scripts/deployment.rb:158:in `create'
13: from /usr/local/bundle/bundler/gems/aws-ruby-0546dfa266fa/lib/openstax/aws/stack.rb:61:in `create'
12: from /usr/local/bundle/bundler/gems/aws-ruby-0546dfa266fa/lib/openstax/aws/secrets_set.rb:9:in `create'
11: from /usr/local/bundle/bundler/gems/aws-ruby-0546dfa266fa/lib/openstax/aws/secrets_set.rb:9:in `each'
10: from /usr/local/bundle/bundler/gems/aws-ruby-0546dfa266fa/lib/openstax/aws/secrets.rb:44:in `create'
9: from /usr/local/bundle/bundler/gems/aws-ruby-0546dfa266fa/lib/openstax/aws/ …
```
=> Adding short sleep

README.md, lib/openstax/aws/deployment_base.rb, spec/deployment_base_spec.rb
See README.
Prior versions of the tag implementation may have had a bug, so probably good to use this version.
=> Allow block form of `tag` on deployment classes

lib/openstax/aws/deployment_base.rb, spec/deployment_base_spec.rb
Add a DeploymentBase#stacks method for accessing a list of stacks in the deployment object instead of having to access them by their individual names.
=> Add a DeploymentBase#stacks method for accessing a list of stacks

README.md, lib/openstax/aws/stack.rb, lib/openstax_aws.rb, spec/stack_spec.rb
I've decided to increase the default amount of attempts (from 120) because i felt like increasing the polling time is not the way to go.
I'm not exactly sure how to test if it works. I've based it on the documentation.
for: https://app.zenhub.com/workspaces/openstax-unified-5b71aabe3815ff014b102258/issues/openstax/unified/942
=> Extend timeout for distribution updates

lib/openstax/aws/deployment_base.rb, spec/deployment_base_spec.rb
Previously if you defined a tag in a parent deployment class, it didn't percolate down to the child class, e.g. this didn't work:
```ruby
class ParentDeployment < OpenStax::Aws::DeploymentBase
tag :foo, "bar"
end
class ChildDeployment < ParentDeployment
end
```
The `DeploymentBase` class uses a class **instance** variable to store the tags.  Class instance variables are not shared through inheritance, which is why `:foo` is not a tag known to `ChildDeployment` above.  We could try to make the tags available to child classes by changing the variable it to a class variable, but then tags would be shared across different child classes, which is not good.
Instead, we kept using a class **instance** variable and added a hook to copy that parent's class instance variable to the child class when …
=> allow tags definitions in parent deployment classes

lib/openstax/aws/tag.rb, spec/tag_spec.rb
IAM only accepts tag values that match the pattern `[\p{L}\p{Z}\p{N}_.:/=+\-@]*`, and so will reject anything with a comma or semicolon.
=> Disallow comma, semicolon in tag value

lib/openstax/aws/packer_1_4_1.rb
there were some control codes being captured on the end of this line that were breaking everything but very hard to catch because they don't show up in a terminal
=> fix packer stdout

lib/openstax/aws/image.rb
=> Restrict AMI search to images owned by us

CHANGELOG.md, README.md, lib/openstax/aws/packer_1_2_5.rb, lib/openstax/aws/packer_1_4_1.rb, lib/openstax/aws/version.rb
Packer's debug mode prints lines that do not end on a newline and then waits for the user to press Enter.
Since aws-ruby was waiting for a whole line to print, these lines were not printing and Packer would sit there waiting for Enter with no indication to the user.
=> Fix Packer debugging by using getc instead of gets and unbuffered mode

lib/openstax/aws/secrets.rb
When we generate those random parameters, they are usually sensitive, even if they are not RSA keys.
SecureString will encrypt them with the account's default KMS key.
=> Encrypt parameters by default (Type: SecureString)

CHANGELOG.md
Nothing should be breaking unless someone was testing that the Packer calls returned nil (probably not).
=> Added more missing unreleased changelog entries

lib/openstax/aws/distribution.rb
for: https://app.zenhub.com/workspaces/openstax-unified-5b71aabe3815ff014b102258/issues/openstax/unified/1537
https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/CloudFront/Waiters/InvalidationCompleted.html
=> Set max_attempts for invalidation to 60 - increase from default 30

lib/openstax/aws/git_helper.rb, lib/openstax/aws/packer_1_4_1.rb
If packer's manifest post-processor is not configured, then configure it
Should fix whatever problem is preventing the AMI ID output from working currently
=> Read the AMI ID from packer's manifest instead of the human-readable output

lib/openstax/aws/build_image_command_1.rb, lib/openstax/aws/git_helper.rb, lib/openstax/aws/image.rb
- Pass the deployment_sha to packer so the AMI can be tagged with it
- Allow AMI search to find AMIs with a specific deployment version
- Added a current_sha Git helper
Need this new deployment_sha tag to properly filter for AMIs that have been built using the correct deployment version
=> AMIs tagged with deployment script SHA

lib/openstax/aws/build_image_command_1.rb, lib/openstax/aws/git_helper.rb, lib/openstax/aws/version.rb
We'll just make BuildImageCommand1 not set the packer var if the parameter is not passed in
=> Fixed/renamed the current_sha helper

lib/openstax/aws/version.rb, lib/openstax_aws.rb
`get_caller_identity` will also throw a much better error message if the token is expired
=> Provide more details in error messages
